"use client";
// import type { Metadata } from "next";
// import { Barlow } from "next/font/google";
import "./globals.css";
import MainWrapper from "./_components/layout/MainWrapper";
// const inter = Inter({ subsets: ["latin"] });
// const barlow = Barlow({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "500", "600", "800", "900"],
// });
// Import Context (provider only)
import GlobalContextProvider from "./_context/GlobalContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <GlobalContextProvider>
        <body>
        <MainWrapper>{children}</MainWrapper>
        </body>
      </GlobalContextProvider>
    </html>
  );
}