import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./_components/SideNav/SideNav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex gap-4">
        <SideNav />
        {children}
      </body>
    </html>
  );
}
