"use client";
// import type { Metadata } from "next";
// import { Barlow } from "next/font/google";
import "./globals.css";
import SideNav from "./_components/SideNav/SideNav";
import { useState } from "react";
import SubscribedServices from "./_components/SubscribedServices/SubscribedServices";
// Import Context (provider only)
import GlobalContextProvider from "./_context/GlobalContext";

// const barlow = Barlow({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "500", "600", "800", "900"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState<boolean>(false);

  return (
    <html lang="en">
      <GlobalContextProvider>
        <body>
          <div
            className={"mainWrapper h-[100vh] w-[100vw] flex overflow-hidden"}
          >
            <SideNav open={open} setOpen={setOpen} />
            {/* dynamic width */}
            <div className={` ${open && "navOpened"} pageWrapper`}>
              {/* header */}
              <SubscribedServices />
              <div className="pageContent">{children}</div>
            </div>
          </div>
        </body>
      </GlobalContextProvider>
    </html>
  );
}
